// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Unloader is an autogenerated mock type for the Unloader type
type Unloader struct {
	mock.Mock
}

// JobWentMissing provides a mock function with given fields: jobID
func (_m *Unloader) JobWentMissing(jobID int32) {
	_m.Called(jobID)
}
